### ISSUE TITLE
Возможность заменить имя репозитория

### ISSUE THREAD

**Issue by kimrgrey** [btd/luna#51]
Хотелось бы иметь возможность заменить сгенерированное автоматически имя папки на что-нибудь удобочитаемое, с учетом риска пересечься с именами других репозиториев.

**Comment by btd** [comment]
Думаю бесполезно так как тебе надо будет еще и знать где базовая папка репозитория. По моему имеет смысл вывести полный путь, только он нужен для интеграции

**Comment by kimrgrey** [comment]
Ну, это как посмотреть.У меня на сервере расположена папка, в которой валяются репозитории Git + Gitosis для доступа со стороны. Что не очень удобно. И я хочу применить твою тулзу для упрощения администрирования. Но я  не хочу, чтобы мои славные папочки с проектами были переименованы в A21B97835ZZ. Совсем не хочу :-( Да и вообще, мне нравится называть вещи хорошими именами. Итого, две фичи: импортирование существующих репозиториев и задание имен тем, которые я создал уже через Луну. На первую тоже могу завести issue.

**Comment by btd** [comment]
Это уже сейчас будет работать, мне не хочется городить огород в основном коде. Нужно просто проставить одну переменную в mongo на путь к репе и все.
