### ISSUE TITLE
Адреса репозиториев не оканчиваются на .git

### ISSUE THREAD

**Issue by kimrgrey** [btd/luna#64]
По общепринятому соглашеню адреса bare репозиториев Git должны заканчиваться расширением .git. Пруфлинком можно, наверное, считать Pro Git, страница 66: "By convention, bare repository directories end in .git".

**Comment by btd** [comment]
Я знаю, но не хочу =) Не вижу никакого глобального смысла в этом.

**Comment by kimrgrey** [comment]
Ну, не стоит недооценивать слово "convention", сам понимаешь. Мне лично, как человеку плотно работающему с Git, очень взгляд режет. Глобального смысла во многих соглашениях нет. Но они появились. Если хочешь, можем отследить, почему так получилось, что добавляют .git.

**Comment by btd** [comment]
Я думаю, что добавляют из за того, что  bare репозиторий это папка .git для обычного по сути (ну и выкинутый хлам)

**Comment by kimrgrey** [comment]
Возможно. Все таки мне кажется, что оригинальность - это хорошо, но не в таких вопросах :)
